### PR TITLE
Add support for Resource Owner Credential Flow and code authorization flow

### PR DESCRIPTION
**Pull request by andrejohansson**
I meant to send these as separate pull requests but apparently my GitHub knowledge is not that good.
The commits messages however are fairly clean in their description.

Thanks for your effort with this library.

### CODE REVIEW

**Comment by andrejohansson** [comment]
The build fails because of a missing lock file, I do not think these commits are responsible for that, cheers!

**Comment by stuartbfs** [comment]
Thanks will investigate

**Comment by andrejohansson** [comment]
Super! Could you notify me if/when there is a new nuget package available?

**Comment by stuartbfs** [comment]
Version 4.1.46 should be on nuget now

**Comment by andrejohansson** [comment]
Super, thank you!

**Pull request merged**
